/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardResponsesRouteImport } from './routes/dashboard.responses'
import { Route as DashboardQuizRouteImport } from './routes/dashboard.quiz'
import { Route as DashboardQrcodeRouteImport } from './routes/dashboard.qrcode'
import { Route as DashboardAnalyseRouteImport } from './routes/dashboard.analyse'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResponsesRoute = DashboardResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizRoute = DashboardQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrcodeRoute = DashboardQrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyseRoute = DashboardAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/analyse': typeof DashboardAnalyseRoute
  '/dashboard/qrcode': typeof DashboardQrcodeRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/responses': typeof DashboardResponsesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/analyse': typeof DashboardAnalyseRoute
  '/dashboard/qrcode': typeof DashboardQrcodeRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/responses': typeof DashboardResponsesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/analyse': typeof DashboardAnalyseRoute
  '/dashboard/qrcode': typeof DashboardQrcodeRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/responses': typeof DashboardResponsesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard/analyse'
    | '/dashboard/qrcode'
    | '/dashboard/quiz'
    | '/dashboard/responses'
    | '/dashboard/settings'
    | '/quiz/$quizId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard/analyse'
    | '/dashboard/qrcode'
    | '/dashboard/quiz'
    | '/dashboard/responses'
    | '/dashboard/settings'
    | '/quiz/$quizId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard/analyse'
    | '/dashboard/qrcode'
    | '/dashboard/quiz'
    | '/dashboard/responses'
    | '/dashboard/settings'
    | '/quiz/$quizId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/responses': {
      id: '/dashboard/responses'
      path: '/responses'
      fullPath: '/dashboard/responses'
      preLoaderRoute: typeof DashboardResponsesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz': {
      id: '/dashboard/quiz'
      path: '/quiz'
      fullPath: '/dashboard/quiz'
      preLoaderRoute: typeof DashboardQuizRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/qrcode': {
      id: '/dashboard/qrcode'
      path: '/qrcode'
      fullPath: '/dashboard/qrcode'
      preLoaderRoute: typeof DashboardQrcodeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analyse': {
      id: '/dashboard/analyse'
      path: '/analyse'
      fullPath: '/dashboard/analyse'
      preLoaderRoute: typeof DashboardAnalyseRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyseRoute: typeof DashboardAnalyseRoute
  DashboardQrcodeRoute: typeof DashboardQrcodeRoute
  DashboardQuizRoute: typeof DashboardQuizRoute
  DashboardResponsesRoute: typeof DashboardResponsesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyseRoute: DashboardAnalyseRoute,
  DashboardQrcodeRoute: DashboardQrcodeRoute,
  DashboardQuizRoute: DashboardQuizRoute,
  DashboardResponsesRoute: DashboardResponsesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
